# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online  # noqa: E501

    OpenAPI spec version: 1.7.15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.bad_request import BadRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestBadRequest(unittest.TestCase):
    """BadRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBadRequest(self):
        """Test BadRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.bad_request.BadRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
