# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online  # noqa: E501

    OpenAPI spec version: 1.7.15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.routes_api import RoutesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRoutesApi(unittest.TestCase):
    """RoutesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.routes_api.RoutesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_route_origin_destination(self):
        """Test case for get_route_origin_destination

        Get route  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
