# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online  # noqa: E501

    OpenAPI spec version: 1.7.15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.wallet_api import WalletApi  # noqa: E501
from swagger_client.rest import ApiException


class TestWalletApi(unittest.TestCase):
    """WalletApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.wallet_api.WalletApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_characters_character_id_wallet(self):
        """Test case for get_characters_character_id_wallet

        Get a character's wallet balance  # noqa: E501
        """
        pass

    def test_get_characters_character_id_wallet_journal(self):
        """Test case for get_characters_character_id_wallet_journal

        Get character wallet journal  # noqa: E501
        """
        pass

    def test_get_characters_character_id_wallet_transactions(self):
        """Test case for get_characters_character_id_wallet_transactions

        Get wallet transactions  # noqa: E501
        """
        pass

    def test_get_corporations_corporation_id_wallets(self):
        """Test case for get_corporations_corporation_id_wallets

        Returns a corporation's wallet balance  # noqa: E501
        """
        pass

    def test_get_corporations_corporation_id_wallets_division_journal(self):
        """Test case for get_corporations_corporation_id_wallets_division_journal

        Get corporation wallet journal  # noqa: E501
        """
        pass

    def test_get_corporations_corporation_id_wallets_division_transactions(self):
        """Test case for get_corporations_corporation_id_wallets_division_transactions

        Get corporation wallet transactions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
