# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online  # noqa: E501

    OpenAPI spec version: 1.7.15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.insurance_api import InsuranceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestInsuranceApi(unittest.TestCase):
    """InsuranceApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.insurance_api.InsuranceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_insurance_prices(self):
        """Test case for get_insurance_prices

        List insurance levels  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
