# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online  # noqa: E501

    OpenAPI spec version: 1.7.15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.wars_api import WarsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestWarsApi(unittest.TestCase):
    """WarsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.wars_api.WarsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_wars(self):
        """Test case for get_wars

        List wars  # noqa: E501
        """
        pass

    def test_get_wars_war_id(self):
        """Test case for get_wars_war_id

        Get war information  # noqa: E501
        """
        pass

    def test_get_wars_war_id_killmails(self):
        """Test case for get_wars_war_id_killmails

        List kills for a war  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
