# coding: utf-8

# flake8: noqa
"""
    EVE Swagger Interface

    An OpenAPI for EVE Online  # noqa: E501

    OpenAPI spec version: 1.7.15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.bad_request import BadRequest
from swagger_client.models.error_limited import ErrorLimited
from swagger_client.models.forbidden import Forbidden
from swagger_client.models.gateway_timeout import GatewayTimeout
from swagger_client.models.internal_server_error import InternalServerError
from swagger_client.models.service_unavailable import ServiceUnavailable
from swagger_client.models.unauthorized import Unauthorized
